ALTER TABLE users ADD COLUMN IF NOT EXISTS pstn_enabled BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS pstn_daily_limit INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD CONSTRAINT users_pstn_daily_limit_check CHECK (pstn_daily_limit BETWEEN 0 AND 1000);
