[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0

[dinstar-gateway]
type=endpoint
context=from-dinstar
disallow=all
allow=ulaw,alaw,gsm,g729
aors=dinstar-gateway
identify/endpoint=dinstar-gateway

[dinstar-gateway]
type=aor
contact=sip:192.168.1.100:5060 ; عنوان IP جهاز DINSTAR المحلي

[dinstar-gateway]
type=identify
endpoint=dinstar-gateway
match=192.168.1.100
